"""MediaMTX (or other) RTSP server process management."""

from __future__ import annotations

import socket
import subprocess
import time
from pathlib import Path

from easy_rtsp.exceptions import DependencyError, PublishError
from easy_rtsp.ffmpeg_util import resolve_mediamtx


def discover_webrtc_additional_hosts() -> list[str]:
    """
    IPs to advertise in ICE for local MediaMTX WebRTC.

    Browsers need candidates that match how they reach the server (e.g. ``127.0.0.1`` for the
    same machine, LAN IP for phones). MediaMTX also recommends ``webrtcAdditionalHosts`` when
    connectivity fails behind NAT or strict firewalls.
    """
    out: list[str] = []
    seen: set[str] = set()

    def add(ip: str) -> None:
        if ip in seen:
            return
        # Skip APIPA / link-local noise from some Windows adapters.
        if ip.startswith("169.254."):
            return
        seen.add(ip)
        out.append(ip)

    add("127.0.0.1")
    try:
        _hn, _aliaslist, ipaddrs = socket.gethostbyname_ex(socket.gethostname())
        for ip in ipaddrs:
            if ip.startswith("127."):
                continue
            add(ip)
    except OSError:
        pass
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            s.settimeout(0.2)
            s.connect(("8.8.8.8", 80))
            add(s.getsockname()[0])
        finally:
            s.close()
    except OSError:
        pass
    return out


def tcp_port_is_available(host: str, port: int) -> bool:
    """Return True if we can bind to ``host:port`` (nothing listening yet)."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            s.bind((host, port))
        except OSError:
            return False
        return True


def write_minimal_mediamtx_config(
    path: Path,
    rtsp_path: str,
    listen_port: int,
    *,
    webrtc_enabled: bool = False,
    webrtc_http_port: int = 8889,
) -> None:
    """Write a minimal MediaMTX config: RTSP publisher path and optional WebRTC (browser) playback."""
    if webrtc_enabled:
        hosts = discover_webrtc_additional_hosts()
        hosts_yaml = ", ".join(hosts)
        # - webrtcIPsFromInterfaces: false — on Windows, auto-discovered IPs often include VPN /
        #   virtual adapters; the browser then negotiates ICE candidates that never reach 127.0.0.1.
        # - webrtcICEServers2: [] — STUN is for NAT hole-punching; for same-machine / LAN it can
        #   make browsers prefer srflx candidates and stay stuck on "loading". Static UDP :8189
        #   + host candidates in webrtcAdditionalHosts is enough for typical local playback.
        webrtc_block = f"""
webrtc: true
webrtcAddress: :{webrtc_http_port}
webrtcIPsFromInterfaces: false
webrtcLocalUDPAddress: :8189
webrtcLocalTCPAddress: :8189
webrtcAdditionalHosts: [{hosts_yaml}]
webrtcICEServers2: []
"""
    else:
        webrtc_block = "\nwebrtc: false\n"

    content = f"""# Generated by easy-rtsp
logLevel: warn
logDestinations: [stdout]
rtspAddress: :{listen_port}
{webrtc_block}
paths:
  {rtsp_path}:
    source: publisher
"""
    path.write_text(content, encoding="utf-8")


class MediaMTXProcess:
    """Started ``mediamtx`` subprocess with a generated config file."""

    def __init__(self, process: subprocess.Popen[bytes], config_path: Path) -> None:
        self._process = process
        self._config_path = config_path

    @property
    def pid(self) -> int | None:
        return self._process.pid

    def stop(self, *, timeout: float = 10.0) -> None:
        if self._process.poll() is None:
            self._process.terminate()
            try:
                self._process.wait(timeout=timeout)
            except subprocess.TimeoutExpired:
                self._process.kill()
        try:
            if self._config_path.exists():
                self._config_path.unlink()
        except OSError:
            pass

    @classmethod
    def start(cls, config_path: Path) -> MediaMTXProcess:
        binary = resolve_mediamtx()
        if not binary:
            raise DependencyError(
                "mediamtx not found on PATH. Install MediaMTX and add it to PATH, "
                "or set EASY_RTSP_MEDIAMTX to the mediamtx executable."
            )
        try:
            proc = subprocess.Popen(
                [binary, str(config_path)],
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
            )
        except FileNotFoundError as e:
            raise DependencyError("mediamtx could not be executed.") from e
        time.sleep(0.15)
        if proc.poll() is not None:
            err = (proc.stderr.read() or b"").decode("utf-8", errors="replace")
            raise PublishError(f"mediamtx exited immediately (code {proc.returncode}): {err[-2000:]}")
        return cls(proc, config_path)
